export const mockUsers = {
  1: {
    id: 1,
    name: 'Matcha',
    email: 'matcha@example.com',
    level: 'CREATOR',
    points: 450,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=matcha',
    createdAt: '2024-01-15',
  },
}

export const mockTasks = [
  {
    id: 1,
    title: '每日登入',
    description: '每日登入一次即可完成',
    points: 10,
    category: 'daily',
    completed: true,
    icon: '🌅',
    frequency: 'daily',
  },
  {
    id: 2,
    title: '完成任務清單',
    description: '完成 3 項以上任務',
    points: 20,
    category: 'milestone',
    completed: false,
    icon: '✅',
    frequency: 'weekly',
  },
  {
    id: 3,
    title: '申辦數位帳戶',
    description: '成功申辦數位帳戶',
    points: 100,
    category: 'banking',
    completed: false,
    icon: '🏦',
    frequency: 'once',
  },
  {
    id: 4,
    title: '使用行動支付',
    description: '使用行動支付完成一筆交易',
    points: 30,
    category: 'banking',
    completed: false,
    icon: '📱',
    frequency: 'daily',
  },
  {
    id: 5,
    title: '閱讀永續金融專欄',
    description: '完成永續金融知識學習',
    points: 20,
    category: 'esg',
    completed: false,
    icon: '🌱',
    frequency: 'weekly',
  },
  {
    id: 6,
    title: '推薦好友',
    description: '邀請好友註冊成功',
    points: 30,
    category: 'social',
    completed: false,
    icon: '👥',
    frequency: 'unlimited',
  },
]

export const mockRewards = [
  // 🌱 永續探索系列 - Lv1 Explorer 專屬
  {
    id: 1,
    title: '環保帆布袋',
    points: 50,
    image: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=400&h=300&fit=crop',
    category: 'sustainable',
    series: 'sustainable',
    level: 'EXPLORER',
    stock: 150,
    actualStock: 150,
    stockStatus: 'sufficient',
    description: '有機棉材質，印刷品牌 LOGO',
    marketPrice: 'NT$200-300',
    levelRestriction: 'lv1_only',
  },
  {
    id: 2,
    title: '竹纖維餐具組',
    points: 80,
    image: 'https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=400&h=300&fit=crop',
    category: 'sustainable',
    series: 'sustainable',
    level: 'EXPLORER',
    stock: 120,
    actualStock: 120,
    stockStatus: 'sufficient',
    description: '筷子+湯匙+收納袋',
    marketPrice: 'NT$300-400',
    levelRestriction: 'lv1_only',
  },
  {
    id: 3,
    title: '再生紙筆記本',
    points: 70,
    image: 'https://images.unsplash.com/photo-1584012691470-e50c4719a898?w=400&h=300&fit=crop',
    category: 'sustainable',
    series: 'sustainable',
    level: 'EXPLORER',
    stock: 130,
    actualStock: 130,
    stockStatus: 'sufficient',
    description: 'A5 尺寸、環保紙張',
    marketPrice: 'NT$250-350',
    levelRestriction: 'lv1_only',
  },
  {
    id: 4,
    title: '種子鉛筆組',
    points: 40,
    image: 'https://images.unsplash.com/photo-1585066264859-d3eab4b253e2?w=400&h=300&fit=crop',
    category: 'sustainable',
    series: 'sustainable',
    level: 'EXPLORER',
    stock: 140,
    actualStock: 140,
    stockStatus: 'sufficient',
    description: '5入，用完可種植的鉛筆',
    marketPrice: 'NT$150-200',
    levelRestriction: 'lv1_only',
  },
  {
    id: 5,
    title: '多肉植物盆栽',
    points: 100,
    image: 'https://images.unsplash.com/photo-1509937528035-ad76254b0356?w=400&h=300&fit=crop',
    category: 'sustainable',
    series: 'sustainable',
    level: 'EXPLORER',
    stock: 68,
    actualStock: 68,
    stockStatus: 'moderate',
    description: '含陶瓷盆+植物',
    marketPrice: 'NT$400-500',
    levelRestriction: 'lv1_only',
  },
  {
    id: 6,
    title: '以你之名種一棵樹',
    points: 120,
    image: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=400&h=300&fit=crop',
    category: 'sustainable',
    series: 'sustainable',
    level: 'EXPLORER',
    stock: 200,
    actualStock: 200,
    stockStatus: 'sufficient',
    description: '獲得電子證書+GPS定位',
    marketPrice: 'NT$500-800',
    levelRestriction: 'lv1_only',
  },

  // 🪴 質感創造系列 - Lv2 Creator 專屬
  {
    id: 7,
    title: '社企手工皮革卡夾',
    points: 200,
    image: 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=400&h=300&fit=crop',
    category: 'quality',
    series: 'quality',
    level: 'CREATOR',
    stock: 32,
    actualStock: 32,
    stockStatus: 'limited',
    description: '植鞣皮、職人手作',
    marketPrice: 'NT$800-1,200',
    levelRestriction: 'lv2_plus',
  },
  {
    id: 8,
    title: '雙層玻璃隨行杯',
    points: 250,
    image: 'https://images.unsplash.com/photo-1514432324607-2e467f4af445?w=400&h=300&fit=crop',
    category: 'quality',
    series: 'quality',
    level: 'CREATOR',
    stock: 110,
    actualStock: 110,
    stockStatus: 'sufficient',
    description: '350ml、防燙設計',
    marketPrice: 'NT$800-1,200',
    levelRestriction: 'lv2_plus',
  },
  {
    id: 9,
    title: '香氛蠟燭禮盒',
    points: 220,
    image: 'https://images.unsplash.com/photo-1602874801006-52c87677b5f1?w=400&h=300&fit=crop',
    category: 'quality',
    series: 'quality',
    level: 'CREATOR',
    stock: 75,
    actualStock: 75,
    stockStatus: 'moderate',
    description: '3入、天然大豆蠟',
    marketPrice: 'NT$800-1,000',
    levelRestriction: 'lv2_plus',
  },
  {
    id: 10,
    title: '無線充電盤',
    points: 280,
    image: 'https://images.unsplash.com/photo-1591290619762-c588085ade74?w=400&h=300&fit=crop',
    category: 'quality',
    series: 'quality',
    level: 'CREATOR',
    stock: 58,
    actualStock: 58,
    stockStatus: 'moderate',
    description: '竹製外殼、環保材質',
    marketPrice: 'NT$1,000-1,500',
    levelRestriction: 'lv2_plus',
  },
  {
    id: 11,
    title: '運動水壺',
    points: 180,
    image: 'https://images.unsplash.com/photo-1602143407249-1e6c20e0d22f?w=400&h=300&fit=crop',
    category: 'quality',
    series: 'quality',
    level: 'CREATOR',
    stock: 125,
    actualStock: 125,
    stockStatus: 'sufficient',
    description: '750ml、防漏設計',
    marketPrice: 'NT$600-800',
    levelRestriction: 'lv2_plus',
  },
  {
    id: 12,
    title: '瑜珈墊',
    points: 400,
    image: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=400&h=300&fit=crop',
    category: 'quality',
    series: 'quality',
    level: 'CREATOR',
    stock: 18,
    actualStock: 18,
    stockStatus: 'limited',
    description: '天然橡膠、6mm厚',
    marketPrice: 'NT$1,500-2,000',
    levelRestriction: 'lv2_plus',
  },

  // 🕯️ 美學先鋒系列 - Lv3 Visionary 專屬
  {
    id: 13,
    title: 'LAMY Safari 鋼筆',
    points: 600,
    image: 'https://images.unsplash.com/photo-1611532736579-6b16e2b50449?w=400&h=300&fit=crop',
    category: 'aesthetic',
    series: 'aesthetic',
    level: 'VISIONARY',
    stock: 25,
    actualStock: 25,
    stockStatus: 'limited',
    description: '經典系列',
    marketPrice: 'NT$1,500-2,000',
    levelRestriction: 'lv3_plus',
  },
  {
    id: 14,
    title: 'Moleskine 筆記本',
    points: 450,
    image: 'https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=400&h=300&fit=crop',
    category: 'aesthetic',
    series: 'aesthetic',
    level: 'VISIONARY',
    stock: 82,
    actualStock: 82,
    stockStatus: 'moderate',
    description: '經典黑色硬殼本',
    marketPrice: 'NT$800-1,000',
    levelRestriction: 'lv3_plus',
  },
  {
    id: 15,
    title: '無印良品香氛機',
    points: 700,
    image: 'https://images.unsplash.com/photo-1585206594135-4a0a9db89468?w=400&h=300&fit=crop',
    category: 'aesthetic',
    series: 'aesthetic',
    level: 'VISIONARY',
    stock: 15,
    actualStock: 15,
    stockStatus: 'limited',
    description: '超音波擴香',
    marketPrice: 'NT$2,500-3,500',
    levelRestriction: 'lv3_plus',
  },
  {
    id: 16,
    title: '降噪耳機',
    points: 900,
    image: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=400&h=300&fit=crop',
    category: 'aesthetic',
    series: 'aesthetic',
    level: 'VISIONARY',
    stock: 12,
    actualStock: 12,
    stockStatus: 'limited',
    description: 'SONY/Bose 入門款',
    marketPrice: 'NT$4,000-6,000',
    levelRestriction: 'lv3_plus',
  },
  {
    id: 17,
    title: '極簡後背包',
    points: 800,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=300&fit=crop',
    category: 'aesthetic',
    series: 'aesthetic',
    level: 'VISIONARY',
    stock: 20,
    actualStock: 20,
    stockStatus: 'limited',
    description: '防潑水、可裝15吋筆電',
    marketPrice: 'NT$3,000-4,000',
    levelRestriction: 'lv3_plus',
  },
  {
    id: 18,
    title: '設計師太陽眼鏡',
    points: 650,
    image: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=400&h=300&fit=crop',
    category: 'aesthetic',
    series: 'aesthetic',
    level: 'VISIONARY',
    stock: 28,
    actualStock: 28,
    stockStatus: 'limited',
    description: '抗UV400',
    marketPrice: 'NT$2,500-4,000',
    levelRestriction: 'lv3_plus',
  },

  // 💼 品味閃耀系列 - Lv4 Luminary 專屬
  {
    id: 19,
    title: 'LAMY 2000 鋼筆',
    points: 1500,
    image: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=400&h=300&fit=crop',
    category: 'premium',
    series: 'premium',
    level: 'LUMINARY',
    stock: 25,
    actualStock: 25,
    stockStatus: 'limited',
    description: '經典黑檀木款',
    marketPrice: 'NT$4,000-5,000',
    levelRestriction: 'lv4_only',
  },
  {
    id: 20,
    title: '真皮公事包',
    points: 2000,
    image: 'https://images.unsplash.com/photo-1548592806-6f7a9800e096?w=400&h=300&fit=crop',
    category: 'premium',
    series: 'premium',
    level: 'LUMINARY',
    stock: 18,
    actualStock: 18,
    stockStatus: 'limited',
    description: '頭層牛皮、可裝筆電',
    marketPrice: 'NT$6,000-8,000',
    levelRestriction: 'lv4_only',
  },
  {
    id: 21,
    title: '米其林餐廳雙人餐券',
    points: 2500,
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400&h=300&fit=crop',
    category: 'premium',
    series: 'premium',
    level: 'LUMINARY',
    stock: 12,
    actualStock: 12,
    stockStatus: 'limited',
    description: '指定餐廳',
    marketPrice: 'NT$8,000-12,000',
    levelRestriction: 'lv4_only',
  },
  {
    id: 22,
    title: '五星飯店住宿券',
    points: 3000,
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=300&fit=crop',
    category: 'premium',
    series: 'premium',
    level: 'LUMINARY',
    stock: 15,
    actualStock: 15,
    stockStatus: 'limited',
    description: '雙人房一晚',
    marketPrice: 'NT$10,000-15,000',
    levelRestriction: 'lv4_only',
  },
  {
    id: 23,
    title: 'AirPods Pro 3',
    points: 3000,
    image: 'https://images.unsplash.com/photo-1606841837239-c5a1a4a07af7?w=400&h=300&fit=crop',
    category: 'premium',
    series: 'premium',
    level: 'LUMINARY',
    stock: 6,
    actualStock: 6,
    stockStatus: 'rare',
    description: '主動降噪、空間音訊',
    marketPrice: 'NT$7,990',
    levelRestriction: 'lv4_only',
  },
  {
    id: 24,
    title: 'Apple Watch Series 10',
    points: 5000,
    image: 'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=400&h=300&fit=crop',
    category: 'premium',
    series: 'premium',
    level: 'LUMINARY',
    stock: 3,
    actualStock: 3,
    stockStatus: 'rare',
    description: '最新款智慧手錶',
    marketPrice: 'NT$13,900',
    levelRestriction: 'lv4_only',
  },
]

export const mockOrders = [
  {
    id: 'ORD-001',
    rewardId: 1,
    rewardTitle: 'LAMY 鋼筆',
    pointsSpent: 300,
    status: 'delivered',
    createdAt: '2024-11-05',
    deliveredAt: '2024-11-08',
  },
  {
    id: 'ORD-002',
    rewardId: 3,
    rewardTitle: '竹製用品組',
    pointsSpent: 150,
    status: 'shipped',
    createdAt: '2024-11-08',
    deliveredAt: null,
  },
]

export const levelConfig = [
  {
    level: 'EXPLORER',
    name: '探索者',
    minPoints: 0,
    color: '#10b981',
    bgColor: '#d1fae5',
  },
  {
    level: 'CREATOR',
    name: '創造者',
    minPoints: 300,
    color: '#3b82f6',
    bgColor: '#dbeafe',
  },
  {
    level: 'VISIONARY',
    name: '先行者',
    minPoints: 800,
    color: '#f59e0b',
    bgColor: '#fef3c7',
  },
  {
    level: 'LUMINARY',
    name: '閃耀者',
    minPoints: 1500,
    color: '#a78bfa',
    bgColor: '#ede9fe',
  },
]