export const mockUsers = {
  1: {
    id: 1,
    name: 'Matcha',
    email: 'matcha@example.com',
    level: 'CREATOR',
    levelPoints: 700,    // 升級積分 - 只能加不能減，用於提升會員等級
    rewardPoints: 600,   // 兌換積分 - 可扣除，用於兌換禮品
    points: 600, // 保留舊字段以維持向後兼容
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=matcha',
    createdAt: '2024-01-15',
    // 統計數據
    stats: {
      tasksCompleted: 23,
      consecutiveDays: 7,
      totalLogins: 45,
      rewardsRedeemed: 3,
      friendsInvited: 2
    }
  },
}

export const mockTasks = [
  // 📱 日常互動任務 (6個)
  { id: 1, title: '每日登入', description: '每日登入一次即可完成', levelPoints: 5, rewardPoints: 10, category: 'daily', level: '全等級', completed: false, icon: '🌅', frequency: '每日' },
  { id: 2, title: '完善個人資料', description: '完整填寫個人資料可獲得積分', levelPoints: 30, rewardPoints: 50, category: 'daily', level: '全等級', completed: false, icon: '👤', frequency: '一次性' },
  { id: 3, title: '連續3天登入', description: '連續3天登入系統', levelPoints: 20, rewardPoints: 30, category: 'daily', level: '全等級', completed: false, icon: '🔥', frequency: '可重複' },
  { id: 4, title: '連續7天登入', description: '連續7天登入系統', levelPoints: 50, rewardPoints: 80, category: 'daily', level: 'Lv2+', completed: false, icon: '⭐', frequency: '可重複' },
  { id: 5, title: '分享到社群', description: '分享內容到社群媒體', levelPoints: 15, rewardPoints: 20, category: 'daily', level: '全等級', completed: false, icon: '📤', frequency: '每日最多3次' },
  { id: 6, title: '按讚或留言', description: '在內容下方互動', levelPoints: 5, rewardPoints: 8, category: 'daily', level: '全等級', completed: false, icon: '💬', frequency: '每日最多5次' },

  // 💰 理財學習任務 (6個)
  { id: 7, title: '點擊閱讀文章', description: '閱讀理財相關文章', levelPoints: 10, rewardPoints: 15, category: 'financial', level: '全等級', completed: false, icon: '📖', frequency: '每週最多3篇' },
  { id: 8, title: '播放影片', description: '觀看理財教學影片', levelPoints: 15, rewardPoints: 25, category: 'financial', level: '全等級', completed: false, icon: '🎬', frequency: '每週最多3支' },
  { id: 9, title: '完成小測驗', description: '完成理財知識測驗', levelPoints: 25, rewardPoints: 40, category: 'financial', level: '全等級', completed: false, icon: '📝', frequency: '每月最多3次' },
  { id: 10, title: '完成開戶流程說明', description: '觀看開戶說明影片', levelPoints: 50, rewardPoints: 80, category: 'financial', level: '全等級', completed: false, icon: '🏦', frequency: '一次性' },
  { id: 11, title: '訂閱市場分析報告', description: '訂閱接收市場分析', levelPoints: 30, rewardPoints: 50, category: 'financial', level: '全等級', completed: false, icon: '📊', frequency: '一次性' },
  { id: 12, title: '追蹤官方社群', description: '追蹤官方社群平台', levelPoints: 20, rewardPoints: 30, category: 'financial', level: '全等級', completed: false, icon: '👍', frequency: '一次性' },

  // 📊 投資實踐任務 (6個)
  { id: 13, title: '完成風險測驗', description: '完成投資風險評估', levelPoints: 30, rewardPoints: 50, category: 'investment', level: '全等級', completed: false, icon: '⚖️', frequency: '一次性' },
  { id: 14, title: '使用退休計算器', description: '計算退休所需資金', levelPoints: 20, rewardPoints: 35, category: 'investment', level: '全等級', completed: false, icon: '🧮', frequency: '每月最多3次' },
  { id: 15, title: '設定儲蓄目標', description: '設定個人儲蓄目標', levelPoints: 30, rewardPoints: 50, category: 'investment', level: '全等級', completed: false, icon: '🎯', frequency: '一次性' },
  { id: 16, title: '填寫開戶意向調查', description: '填寫開戶意願表單', levelPoints: 100, rewardPoints: 150, category: 'investment', level: '全等級', completed: false, icon: '📋', frequency: '一次性' },
  { id: 17, title: '完善投資偏好', description: '完整填寫投資偏好', levelPoints: 60, rewardPoints: 100, category: 'investment', level: '全等級', completed: false, icon: '💼', frequency: '一次性' },
  { id: 18, title: '預約理專諮詢', description: '預約專業理財諮詢', levelPoints: 150, rewardPoints: 200, category: 'investment', level: 'Lv2+', completed: false, icon: '🤝', frequency: '一次性' },

  // 🌱 永續行動任務 (6個)
  { id: 19, title: '閱讀ESG文章', description: '閱讀永續相關文章', levelPoints: 10, rewardPoints: 15, category: 'esg', level: '全等級', completed: false, icon: '🌱', frequency: '每週最多3篇' },
  { id: 20, title: 'ESG知識測驗', description: '完成ESG知識測驗', levelPoints: 20, rewardPoints: 30, category: 'esg', level: '全等級', completed: false, icon: '♻️', frequency: '每月最多3次' },
  { id: 21, title: '使用碳足跡計算器', description: '計算個人碳足跡', levelPoints: 25, rewardPoints: 40, category: 'esg', level: '全等級', completed: false, icon: '🌍', frequency: '一次性' },
  { id: 22, title: '設定綠色目標', description: '設定環保行動目標', levelPoints: 30, rewardPoints: 50, category: 'esg', level: 'Lv2+', completed: false, icon: '🎋', frequency: '一次性' },
  { id: 23, title: '分享ESG內容', description: '分享永續相關內容', levelPoints: 15, rewardPoints: 25, category: 'esg', level: 'Lv2+', completed: false, icon: 'star', frequency: '每週最多3次' },
  { id: 24, title: '觀看ESG影片', description: '觀看永續教育影片', levelPoints: 15, rewardPoints: 25, category: 'esg', level: '全等級', completed: false, icon: '🎥', frequency: '每週最多3支' },

  // 🎁 社群成就任務 (6個)
  { id: 25, title: '邀請好友註冊', description: '成功邀請好友加入', levelPoints: 50, rewardPoints: 100, category: 'social', level: 'Lv2+', completed: false, icon: '👥', frequency: '無限' },
  { id: 26, title: '首次升級獎勵', description: '達成等級提升', levelPoints: 50, rewardPoints: 80, category: 'social', level: '全等級', completed: false, icon: '🎖️', frequency: '每等級一次' },
  { id: 27, title: '參加線上說明會', description: '報名並參加說明會', levelPoints: 120, rewardPoints: 180, category: 'social', level: 'Lv2+', completed: false, icon: '🎤', frequency: '每次活動' },
  { id: 28, title: '完成新手任務', description: '完成5個基礎任務', levelPoints: 80, rewardPoints: 120, category: 'social', level: 'Lv1', completed: false, icon: '🌟', frequency: '一次性' },
  { id: 29, title: '連續活躍獎勵', description: '當月完成10個以上任務', levelPoints: 100, rewardPoints: 150, category: 'social', level: 'Lv2+', completed: false, icon: '🏆', frequency: '每月' },
  { id: 30, title: '社群貢獻獎', description: '當月互動達20次', levelPoints: 60, rewardPoints: 100, category: 'social', level: 'Lv3+', completed: false, icon: '🎁', frequency: '每月' },
].map(task => ({ ...task, points: task.levelPoints })) // 向後兼容

// 任務分類配色系統
export const categoryColors = {
  daily: {
    name: '日常互動',
    icon: '📱',
    gradient: 'from-blue-400 to-blue-600',
    bg: 'bg-blue-50 dark:bg-blue-900/20',
    text: 'text-blue-600 dark:text-blue-400',
    border: 'border-blue-200 dark:border-blue-800'
  },
  financial: {
    name: '理財學習',
    icon: '💰',
    gradient: 'from-green-400 to-green-600', 
    bg: 'bg-green-50 dark:bg-green-900/20',
    text: 'text-green-600 dark:text-green-400',
    border: 'border-green-200 dark:border-green-800'
  },
  investment: {
    name: '投資實踐',
    icon: '📊',
    gradient: 'from-purple-400 to-purple-600',
    bg: 'bg-purple-50 dark:bg-purple-900/20', 
    text: 'text-purple-600 dark:text-purple-400',
    border: 'border-purple-200 dark:border-purple-800'
  },
  esg: {
    name: '永續行動',
    icon: '🌱',
    gradient: 'from-emerald-400 to-emerald-600',
    bg: 'bg-emerald-50 dark:bg-emerald-900/20',
    text: 'text-emerald-600 dark:text-emerald-400', 
    border: 'border-emerald-200 dark:border-emerald-800'
  },
  social: {
    name: '社群成就',
    icon: '🎁',
    gradient: 'from-orange-400 to-orange-600',
    bg: 'bg-orange-50 dark:bg-orange-900/20',
    text: 'text-orange-600 dark:text-orange-400',
    border: 'border-orange-200 dark:border-orange-800'
  }
}

export const mockRewards = [
  // 🌱 永續探索系列 - Lv1 Explorer (禮品 1-8)
  {
    id: 1,
    title: 'LIFE PEN 種子鉛筆組',
    points: 100,
    image: '/images/gifts/gift-1.jpg',
    category: 'sustainable',
    series: 'sustainable',
    level: 'EXPLORER',
    stock: 99,
    actualStock: 99,
    stockStatus: 'high',
    description: '市價NT$280',
    marketPrice: 'NT$280',
    levelRestriction: 'lv1_only',
  },
  {
    id: 2,
    title: 'UiU 環保便攜吸管組',
    points: 100,
    image: '/images/gifts/gift-2.jpg',
    category: 'sustainable',
    series: 'sustainable',
    level: 'EXPLORER',
    stock: 73,
    actualStock: 73,
    stockStatus: 'medium',
    description: '市價NT$300',
    marketPrice: 'NT$300',
    levelRestriction: 'lv1_only',
  },
  {
    id: 3,
    title: '印花樂 實用環保包袋',
    points: 120,
    image: '/images/gifts/gift-3.jpg',
    category: 'sustainable',
    series: 'sustainable',
    level: 'EXPLORER',
    stock: 65,
    actualStock: 65,
    stockStatus: 'medium',
    description: '市價NT$390',
    marketPrice: 'NT$390',
    levelRestriction: 'lv1_only',
  },
  {
    id: 4,
    title: 'HappyEarth 回收紙筆記本',
    points: 130,
    image: '/images/gifts/gift-4.jpg',
    category: 'sustainable',
    series: 'sustainable',
    level: 'EXPLORER',
    stock: 35,
    actualStock: 35,
    stockStatus: 'low',
    description: '市價NT$400',
    marketPrice: 'NT$400',
    levelRestriction: 'lv1_only',
  },
  {
    id: 5,
    title: '沐muhair 無塑固態洗髮精',
    points: 130,
    image: '/images/gifts/gift-5.jpg',
    category: 'sustainable',
    series: 'sustainable',
    level: 'EXPLORER',
    stock: 85,
    actualStock: 85,
    stockStatus: 'medium',
    description: '市價NT$400',
    marketPrice: 'NT$400',
    levelRestriction: 'lv1_only',
  },
  {
    id: 6,
    title: '簡約托特包',
    points: 150,
    image: '/images/gifts/gift-6.jpg',
    category: 'sustainable',
    series: 'sustainable',
    level: 'EXPLORER',
    stock: 99,
    actualStock: 99,
    stockStatus: 'high',
    description: '市價NT$450',
    marketPrice: 'NT$450',
    levelRestriction: 'lv1_only',
  },
  {
    id: 7,
    title: 'Re-ing 天然竹纖維便當盒',
    points: 150,
    image: '/images/gifts/gift-7.jpg',
    category: 'sustainable',
    series: 'sustainable',
    level: 'EXPLORER',
    stock: 58,
    actualStock: 58,
    stockStatus: 'medium',
    description: '市價NT$450',
    marketPrice: 'NT$450',
    levelRestriction: 'lv1_only',
  },
  {
    id: 8,
    title: 'SUCCULAND 多肉植物',
    points: 200,
    image: '/images/gifts/gift-8.jpg',
    category: 'sustainable',
    series: 'sustainable',
    level: 'EXPLORER',
    stock: 23,
    actualStock: 23,
    stockStatus: 'low',
    description: '市價NT$590',
    marketPrice: 'NT$590',
    levelRestriction: 'lv1_only',
  },

  // 🪴 質感創造系列 - Lv2 Creator (禮品 9-16)
  {
    id: 9,
    title: 'ekax 雲朵筆電包',
    points: 220,
    image: '/images/gifts/gift-9.jpg',
    category: 'quality',
    series: 'quality',
    level: 'CREATOR',
    stock: 99,
    actualStock: 99,
    stockStatus: 'high',
    description: '市價NT$650',
    marketPrice: 'NT$650',
    levelRestriction: 'lv2_plus',
  },
  {
    id: 10,
    title: 'smellscape 擴香石香氛禮盒',
    points: 230,
    image: '/images/gifts/gift-10.jpg',
    category: 'quality',
    series: 'quality',
    level: 'CREATOR',
    stock: 53,
    actualStock: 53,
    stockStatus: 'medium',
    description: '市價NT$700',
    marketPrice: 'NT$700',
    levelRestriction: 'lv2_plus',
  },
  {
    id: 11,
    title: 'MOFT 磁吸感應卡包支架',
    points: 300,
    image: '/images/gifts/gift-11.jpg',
    category: 'quality',
    series: 'quality',
    level: 'CREATOR',
    stock: 24,
    actualStock: 24,
    stockStatus: 'low',
    description: '市價NT$890',
    marketPrice: 'NT$890',
    levelRestriction: 'lv2_plus',
  },
  {
    id: 12,
    title: '手工皮革名片夾',
    points: 310,
    image: '/images/gifts/gift-12.jpg',
    category: 'quality',
    series: 'quality',
    level: 'CREATOR',
    stock: 9,
    actualStock: 9,
    stockStatus: 'critical',
    description: '市價NT$930',
    marketPrice: 'NT$930',
    levelRestriction: 'lv2_plus',
  },
  {
    id: 13,
    title: 'Umbra 臘腸狗戒指收納座',
    points: 310,
    image: '/images/gifts/gift-13.jpg',
    category: 'quality',
    series: 'quality',
    level: 'CREATOR',
    stock: 88,
    actualStock: 88,
    stockStatus: 'medium',
    description: '市價NT$930',
    marketPrice: 'NT$930',
    levelRestriction: 'lv2_plus',
  },
  {
    id: 14,
    title: 'ROOMMI 充電感應垃圾桶',
    points: 320,
    image: '/images/gifts/gift-14.jpg',
    category: 'quality',
    series: 'quality',
    level: 'CREATOR',
    stock: 28,
    actualStock: 28,
    stockStatus: 'low',
    description: '市價NT$959',
    marketPrice: 'NT$959',
    levelRestriction: 'lv2_plus',
  },
  {
    id: 15,
    title: 'KINTO 提式輕巧保溫瓶',
    points: 400,
    image: '/images/gifts/gift-15.jpg',
    category: 'quality',
    series: 'quality',
    level: 'CREATOR',
    stock: 99,
    actualStock: 99,
    stockStatus: 'high',
    description: '市價NT$1148',
    marketPrice: 'NT$1148',
    levelRestriction: 'lv2_plus',
  },
  {
    id: 16,
    title: 'MOMOCONCEPT 保溫杯',
    points: 500,
    image: '/images/gifts/gift-16.jpg',
    category: 'quality',
    series: 'quality',
    level: 'CREATOR',
    stock: 55,
    actualStock: 55,
    stockStatus: 'medium',
    description: '市價NT$1501',
    marketPrice: 'NT$1501',
    levelRestriction: 'lv2_plus',
  },

  // 🕯️ 美學先鋒系列 - Lv3 Visionary (禮品 17-24)
  {
    id: 17,
    title: 'mordeco 轉轉零錢筒',
    points: 530,
    image: '/images/gifts/gift-17.jpg',
    category: 'aesthetic',
    series: 'aesthetic',
    level: 'VISIONARY',
    stock: 36,
    actualStock: 36,
    stockStatus: 'low',
    description: '市價NT$1580',
    marketPrice: 'NT$1580',
    levelRestriction: 'lv3_plus',
  },
  {
    id: 18,
    title: 'Vana 香氛蠟燭暖燈',
    points: 600,
    image: '/images/gifts/gift-18.jpg',
    category: 'aesthetic',
    series: 'aesthetic',
    level: 'VISIONARY',
    stock: 19,
    actualStock: 19,
    stockStatus: 'low',
    description: '市價NT$1790',
    marketPrice: 'NT$1790',
    levelRestriction: 'lv3_plus',
  },
  {
    id: 19,
    title: 'MUJI 超音波芬香噴霧器',
    points: 600,
    image: '/images/gifts/gift-19.jpg',
    category: 'aesthetic',
    series: 'aesthetic',
    level: 'VISIONARY',
    stock: 16,
    actualStock: 16,
    stockStatus: 'low',
    description: '市價NT$1790',
    marketPrice: 'NT$1790',
    levelRestriction: 'lv3_plus',
  },
  {
    id: 20,
    title: 'MOMAX 無線充電行動電源',
    points: 660,
    image: '/images/gifts/gift-20.jpg',
    category: 'aesthetic',
    series: 'aesthetic',
    level: 'VISIONARY',
    stock: 18,
    actualStock: 18,
    stockStatus: 'low',
    description: '市價NT$1980',
    marketPrice: 'NT$1980',
    levelRestriction: 'lv3_plus',
  },
  {
    id: 21,
    title: 'JWAY 砧板刀具烘乾消毒機',
    points: 830,
    image: '/images/gifts/gift-21.jpg',
    category: 'aesthetic',
    series: 'aesthetic',
    level: 'VISIONARY',
    stock: 13,
    actualStock: 13,
    stockStatus: 'low',
    description: '市價NT$2480',
    marketPrice: 'NT$2480',
    levelRestriction: 'lv3_plus',
  },
  {
    id: 22,
    title: 'Oakywood 無線充電盤',
    points: 1100,
    image: '/images/gifts/gift-22.jpg',
    category: 'aesthetic',
    series: 'aesthetic',
    level: 'VISIONARY',
    stock: 49,
    actualStock: 49,
    stockStatus: 'medium',
    description: '市價NT$3200',
    marketPrice: 'NT$3200',
    levelRestriction: 'lv3_plus',
  },
  {
    id: 23,
    title: 'Bellwood 雨傘收納架',
    points: 1100,
    image: '/images/gifts/gift-23.jpg',
    category: 'aesthetic',
    series: 'aesthetic',
    level: 'VISIONARY',
    stock: 22,
    actualStock: 22,
    stockStatus: 'low',
    description: '市價NT$3385',
    marketPrice: 'NT$3385',
    levelRestriction: 'lv3_plus',
  },
  {
    id: 24,
    title: 'Wanu 銜月床頭燈',
    points: 1200,
    image: '/images/gifts/gift-24.jpg',
    category: 'aesthetic',
    series: 'aesthetic',
    level: 'VISIONARY',
    stock: 7,
    actualStock: 7,
    stockStatus: 'critical',
    description: '市價NT$3500',
    marketPrice: 'NT$3500',
    levelRestriction: 'lv3_plus',
  },

  // 💼 品味閃耀系列 - Lv4 Luminary (禮品 25-32)
  {
    id: 25,
    title: '夏慕尼星級饗宴餐券',
    points: 1600,
    image: '/images/gifts/gift-25.jpg',
    category: 'premium',
    series: 'premium',
    level: 'LUMINARY',
    stock: 14,
    actualStock: 14,
    stockStatus: 'low',
    description: '市價NT$4818',
    marketPrice: 'NT$4818',
    levelRestriction: 'lv4_only',
  },
  {
    id: 26,
    title: 'Porter 真皮公事包',
    points: 1950,
    image: '/images/gifts/gift-26.jpg',
    category: 'premium',
    series: 'premium',
    level: 'LUMINARY',
    stock: 18,
    actualStock: 18,
    stockStatus: 'low',
    description: '市價NT$5850',
    marketPrice: 'NT$5850',
    levelRestriction: 'lv4_only',
  },
  {
    id: 27,
    title: 'LAMY 2000 鋼筆',
    points: 2300,
    image: '/images/gifts/gift-27.jpg',
    category: 'premium',
    series: 'premium',
    level: 'LUMINARY',
    stock: 26,
    actualStock: 26,
    stockStatus: 'low',
    description: '市價NT$7020',
    marketPrice: 'NT$7020',
    levelRestriction: 'lv4_only',
  },
  {
    id: 28,
    title: 'AirPods Pro 3',
    points: 2500,
    image: '/images/gifts/gift-28.jpg',
    category: 'premium',
    series: 'premium',
    level: 'LUMINARY',
    stock: 21,
    actualStock: 21,
    stockStatus: 'low',
    description: '市價NT$7490',
    marketPrice: 'NT$7490',
    levelRestriction: 'lv4_only',
  },
  {
    id: 29,
    title: 'Dyson Supersonic 吹風機',
    points: 3300,
    image: '/images/gifts/gift-29.jpg',
    category: 'premium',
    series: 'premium',
    level: 'LUMINARY',
    stock: 5,
    actualStock: 5,
    stockStatus: 'critical',
    description: '市價NT$9999',
    marketPrice: 'NT$9999',
    levelRestriction: 'lv4_only',
  },
  {
    id: 30,
    title: 'Apple Watch Series 11',
    points: 4300,
    image: '/images/gifts/gift-30.jpg',
    category: 'premium',
    series: 'premium',
    level: 'LUMINARY',
    stock: 4,
    actualStock: 4,
    stockStatus: 'critical',
    description: '市價NT$12900',
    marketPrice: 'NT$12900',
    levelRestriction: 'lv4_only',
  },
  {
    id: 31,
    title: 'LOJEL 30吋前開式行李箱',
    points: 4500,
    image: '/images/gifts/gift-31.jpg',
    category: 'premium',
    series: 'premium',
    level: 'LUMINARY',
    stock: 3,
    actualStock: 3,
    stockStatus: 'critical',
    description: '市價NT$13205',
    marketPrice: 'NT$13205',
    levelRestriction: 'lv4_only',
  },
  {
    id: 32,
    title: '雲品尊榮湖景客房住宿券',
    points: 5000,
    image: '/images/gifts/gift-32.jpg',
    category: 'premium',
    series: 'premium',
    level: 'LUMINARY',
    stock: 3,
    actualStock: 3,
    stockStatus: 'critical',
    description: '市價NT$14888',
    marketPrice: 'NT$14888',
    levelRestriction: 'lv4_only',
  },
]

export const mockOrders = [
  {
    id: 'ORD-001',
    rewardId: 1,
    rewardTitle: 'LAMY 鋼筆',
    pointsSpent: 300,
    status: 'delivered',
    createdAt: '2024-11-05',
    deliveredAt: '2024-11-08',
  },
  {
    id: 'ORD-002',
    rewardId: 3,
    rewardTitle: '竹製用品組',
    pointsSpent: 150,
    status: 'shipped',
    createdAt: '2024-11-08',
    deliveredAt: null,
  },
]

export const levelConfig = [
  {
    level: 'EXPLORER',
    name: '探索者',
    levelNumber: 1,
    minPoints: 0,
    maxPoints: 249,
    nextLevelPoints: 250,
    multiplier: 1.0,
    color: '#10b981',
    bgColor: '#d1fae5',
    gradientFrom: 'from-emerald-300',
    gradientTo: 'to-emerald-600',
    icon: 'star'
  },
  {
    level: 'CREATOR',
    name: '創造者',
    levelNumber: 2,
    minPoints: 250,
    maxPoints: 749,
    nextLevelPoints: 750,
    multiplier: 1.15,
    color: '#3b82f6',
    bgColor: '#dbeafe',
    gradientFrom: 'from-cyan-400',
    gradientTo: 'to-blue-500',
    icon: 'star'
  },
  {
    level: 'VISIONARY',
    name: '先行者',
    levelNumber: 3,
    minPoints: 750,
    maxPoints: 1499,
    nextLevelPoints: 1500,
    multiplier: 1.35,
    color: '#f59e0b',
    bgColor: '#fef3c7',
    gradientFrom: 'from-amber-300',
    gradientTo: 'to-amber-600',
    icon: 'star'
  },
  {
    level: 'LUMINARY',
    name: '閃耀者',
    levelNumber: 4,
    minPoints: 1500,
    maxPoints: 999999,
    nextLevelPoints: null,
    multiplier: 1.7,
    color: '#a78bfa',
    bgColor: '#ede9fe',
    gradientFrom: 'from-purple-300',
    gradientTo: 'to-purple-600',
    icon: 'star'
  },
]