export const mockUsers = {
  1: {
    id: 1,
    name: 'Matcha',
    email: 'matcha@example.com',
    level: 'CREATOR',
    levelPoints: 700,    // 升級積分 - 只能加不能減，用於提升會員等級
    rewardPoints: 600,   // 兌換積分 - 可扣除，用於兌換禮品
    points: 600, // 保留舊字段以維持向後兼容
    avatar: 'https://api.dicebear.com/9.x/thumbs/svg?seed=Sarah&backgroundColor=f1f4dc',
    createdAt: '2024-01-15',
    // 統計數據
    stats: {
      tasksCompleted: 23,
      consecutiveDays: 7,
      totalLogins: 45,
      rewardsRedeemed: 3,
      friendsInvited: 2
    }
  },
}

export const mockTasks = [
  // 📱 日常互動任務 (6個)
  { id: 1, title: '每日登入', description: '每日登入一次即可完成', levelPoints: 5, rewardPoints: 10, category: 'daily', level: '全等級', completed: false, icon: '🌅', frequency: '每日' },
  { id: 2, title: '完善個人資料', description: '完整填寫個人資料可獲得積分', levelPoints: 30, rewardPoints: 50, category: 'daily', level: '全等級', completed: false, icon: '👤', frequency: '一次性' },
  { id: 3, title: '連續3天登入', description: '連續3天登入系統', levelPoints: 20, rewardPoints: 30, category: 'daily', level: '全等級', completed: false, icon: '🔥', frequency: '可重複' },
  { id: 4, title: '連續7天登入', description: '連續7天登入系統', levelPoints: 50, rewardPoints: 80, category: 'daily', level: 'Lv2+', completed: false, icon: '⭐', frequency: '可重複' },
  { id: 5, title: '分享到社群', description: '分享內容到社群媒體', levelPoints: 15, rewardPoints: 20, category: 'daily', level: '全等級', completed: false, icon: '📤', frequency: '每日最多3次' },
  { id: 6, title: '按讚或留言', description: '在內容下方互動', levelPoints: 5, rewardPoints: 8, category: 'daily', level: '全等級', completed: false, icon: '💬', frequency: '每日最多5次' },

  // 💰 理財學習任務 (6個)
  { id: 7, title: '點擊閱讀文章', description: '閱讀理財相關文章', levelPoints: 10, rewardPoints: 15, category: 'financial', level: '全等級', completed: false, icon: '📖', frequency: '每週最多3篇' },
  { id: 8, title: '播放影片', description: '觀看理財教學影片', levelPoints: 15, rewardPoints: 25, category: 'financial', level: '全等級', completed: false, icon: '🎬', frequency: '每週最多3支' },
  { id: 9, title: '完成小測驗', description: '完成理財知識測驗', levelPoints: 25, rewardPoints: 40, category: 'financial', level: '全等級', completed: false, icon: '📝', frequency: '每月最多3次' },
  { id: 10, title: '完成開戶流程說明', description: '觀看開戶說明影片', levelPoints: 50, rewardPoints: 80, category: 'financial', level: '全等級', completed: false, icon: '🏦', frequency: '一次性' },
  { id: 11, title: '訂閱市場分析報告', description: '訂閱接收市場分析', levelPoints: 30, rewardPoints: 50, category: 'financial', level: '全等級', completed: false, icon: '📊', frequency: '一次性' },
  { id: 12, title: '追蹤官方社群', description: '追蹤官方社群平台', levelPoints: 20, rewardPoints: 30, category: 'financial', level: '全等級', completed: false, icon: '👍', frequency: '一次性' },

  // 📊 投資實踐任務 (6個)
  { id: 13, title: '完成風險測驗', description: '完成投資風險評估', levelPoints: 30, rewardPoints: 50, category: 'investment', level: '全等級', completed: false, icon: '⚖️', frequency: '一次性' },
  { id: 14, title: '使用退休計算器', description: '計算退休所需資金', levelPoints: 20, rewardPoints: 35, category: 'investment', level: '全等級', completed: false, icon: '🧮', frequency: '每月最多3次' },
  { id: 15, title: '設定儲蓄目標', description: '設定個人儲蓄目標', levelPoints: 30, rewardPoints: 50, category: 'investment', level: '全等級', completed: false, icon: '🎯', frequency: '一次性' },
  { id: 16, title: '填寫開戶意向調查', description: '填寫開戶意願表單', levelPoints: 100, rewardPoints: 150, category: 'investment', level: '全等級', completed: false, icon: '📋', frequency: '一次性' },
  { id: 17, title: '完善投資偏好', description: '完整填寫投資偏好', levelPoints: 60, rewardPoints: 100, category: 'investment', level: '全等級', completed: false, icon: '💼', frequency: '一次性' },
  { id: 18, title: '預約理專諮詢', description: '預約專業理財諮詢', levelPoints: 150, rewardPoints: 200, category: 'investment', level: 'Lv2+', completed: false, icon: '🤝', frequency: '一次性' },

  // 🌱 永續行動任務 (6個)
  { id: 19, title: '閱讀ESG文章', description: '閱讀永續相關文章', levelPoints: 10, rewardPoints: 15, category: 'esg', level: '全等級', completed: false, icon: '🌱', frequency: '每週最多3篇' },
  { id: 20, title: 'ESG知識測驗', description: '完成ESG知識測驗', levelPoints: 20, rewardPoints: 30, category: 'esg', level: '全等級', completed: false, icon: '♻️', frequency: '每月最多3次' },
  { id: 21, title: '使用碳足跡計算器', description: '計算個人碳足跡', levelPoints: 25, rewardPoints: 40, category: 'esg', level: '全等級', completed: false, icon: '🌍', frequency: '一次性' },
  { id: 22, title: '設定綠色目標', description: '設定環保行動目標', levelPoints: 30, rewardPoints: 50, category: 'esg', level: 'Lv2+', completed: false, icon: '🎋', frequency: '一次性' },
  { id: 23, title: '分享ESG內容', description: '分享永續相關內容', levelPoints: 15, rewardPoints: 25, category: 'esg', level: 'Lv2+', completed: false, icon: 'star', frequency: '每週最多3次' },
  { id: 24, title: '觀看ESG影片', description: '觀看永續教育影片', levelPoints: 15, rewardPoints: 25, category: 'esg', level: '全等級', completed: false, icon: '🎥', frequency: '每週最多3支' },

  // 🎁 社群成就任務 (6個)
  { id: 25, title: '邀請好友註冊', description: '成功邀請好友加入', levelPoints: 50, rewardPoints: 100, category: 'social', level: 'Lv2+', completed: false, icon: '👥', frequency: '無限' },
  { id: 26, title: '首次升級獎勵', description: '達成等級提升', levelPoints: 50, rewardPoints: 80, category: 'social', level: '全等級', completed: false, icon: '🎖️', frequency: '每等級一次' },
  { id: 27, title: '參加線上說明會', description: '報名並參加說明會', levelPoints: 120, rewardPoints: 180, category: 'social', level: 'Lv2+', completed: false, icon: '🎤', frequency: '每次活動' },
  { id: 28, title: '完成新手任務', description: '完成5個基礎任務', levelPoints: 80, rewardPoints: 120, category: 'social', level: 'Lv1', completed: false, icon: '🌟', frequency: '一次性' },
  { id: 29, title: '連續活躍獎勵', description: '當月完成10個以上任務', levelPoints: 100, rewardPoints: 150, category: 'social', level: 'Lv2+', completed: false, icon: '🏆', frequency: '每月' },
  { id: 30, title: '社群貢獻獎', description: '當月互動達20次', levelPoints: 60, rewardPoints: 100, category: 'social', level: 'Lv3+', completed: false, icon: '🎁', frequency: '每月' },
].map(task => ({ ...task, points: task.levelPoints })) // 向後兼容

// 任務分類配色系統
export const categoryColors = {
  daily: {
    name: '日常互動',
    icon: '📱',
    gradient: 'from-blue-400 to-blue-600',
    bg: 'bg-blue-50 dark:bg-blue-900/20',
    text: 'text-blue-600 dark:text-blue-400',
    border: 'border-blue-200 dark:border-blue-800'
  },
  financial: {
    name: '理財學習',
    icon: '💰',
    gradient: 'from-green-400 to-green-600',
    bg: 'bg-green-50 dark:bg-green-900/20',
    text: 'text-green-600 dark:text-green-400',
    border: 'border-green-200 dark:border-green-800'
  },
  investment: {
    name: '投資實踐',
    icon: '📊',
    gradient: 'from-purple-400 to-purple-600',
    bg: 'bg-purple-50 dark:bg-purple-900/20',
    text: 'text-purple-600 dark:text-purple-400',
    border: 'border-purple-200 dark:border-purple-800'
  },
  esg: {
    name: '永續行動',
    icon: '🌱',
    gradient: 'from-emerald-400 to-emerald-600',
    bg: 'bg-emerald-50 dark:bg-emerald-900/20',
    text: 'text-emerald-600 dark:text-emerald-400',
    border: 'border-emerald-200 dark:border-emerald-800'
  },
  social: {
    name: '社群成就',
    icon: '🎁',
    gradient: 'from-orange-400 to-orange-600',
    bg: 'bg-orange-50 dark:bg-orange-900/20',
    text: 'text-orange-600 dark:text-orange-400',
    border: 'border-orange-200 dark:border-orange-800'
  }
}

export const mockRewards = [
  // 🌱 永續探索系列 - Lv1 Explorer (禮品 1-8)
  {
    id: 1,
    title: 'LIFE PEN 種子鉛筆組',
    points: 100,
    image: '/images/gifts/gift-1.jpg',
    category: 'sustainable',
    series: 'sustainable',
    level: 'EXPLORER',
    stock: 99,
    actualStock: 99,
    stockStatus: 'high',
    description: '市價NT$280',
    marketPrice: 'NT$280',
    levelRestriction: 'lv1_only',
    details: '環保樹脂製成的種子鉛筆，寫完後可種植於土壤中，發芽成長為真實植物。每組包含5支不同類型的種子鉛筆：番茄、薄荷、向日葵、羅勒和迷迭香。完全可生物分解，是永續生活的最佳選擇。',
  },
  {
    id: 2,
    title: 'UiU 環保便攜吸管組',
    points: 100,
    image: '/images/gifts/gift-2.jpg',
    category: 'sustainable',
    series: 'sustainable',
    level: 'EXPLORER',
    stock: 73,
    actualStock: 73,
    stockStatus: 'medium',
    description: '市價NT$300',
    marketPrice: 'NT$300',
    levelRestriction: 'lv1_only',
    details: '食品級不鏽鋼材質製成，配備便攜布套與專用清潔刷。組合包含直吸管、彎吸管和扁吸管各1支，適應各種飲品容器。耐用性強，可重複使用超過3年，完全避免一次性塑膠吸管污染。是日常外出必備的環保好物。',
  },
  {
    id: 3,
    title: '印花樂 實用環保包袋',
    points: 120,
    image: '/images/gifts/gift-3.jpg',
    category: 'sustainable',
    series: 'sustainable',
    level: 'EXPLORER',
    stock: 65,
    actualStock: 65,
    stockStatus: 'medium',
    description: '市價NT$390',
    marketPrice: 'NT$390',
    levelRestriction: 'lv1_only',
    details: '台灣設計品牌印花樂打造的環保布料包袋，100%有機棉布料製作。印花圖案由設計師手繪，每件都是獨一無二。耐用的雙層結構適合日常購物、外出攜帶，可容納A4大小物品。支持本土設計，體現永續消費的理念。',
  },
  {
    id: 4,
    title: 'HappyEarth 回收紙筆記本',
    points: 130,
    image: '/images/gifts/gift-4.jpg',
    category: 'sustainable',
    series: 'sustainable',
    level: 'EXPLORER',
    stock: 35,
    actualStock: 35,
    stockStatus: 'low',
    description: '市價NT$400',
    marketPrice: 'NT$400',
    levelRestriction: 'lv1_only',
    details: '100%回收紙漿製造的環保筆記本，封面以植物性染料著色。頁數為200頁，線圈裝訂方便翻閱與拆頁。紙質柔和舒適，適合日常手寫筆記、日記或創意記錄。每本購買都支持全球廢紙回收計畫，實踐循環經濟。',
  },
  {
    id: 5,
    title: '沐muhair 無塑固態洗髮精',
    points: 130,
    image: '/images/gifts/gift-5.jpg',
    category: 'sustainable',
    series: 'sustainable',
    level: 'EXPLORER',
    stock: 85,
    actualStock: 85,
    stockStatus: 'medium',
    description: '市價NT$400',
    marketPrice: 'NT$400',
    levelRestriction: 'lv1_only',
    details: '台灣品牌沐muhair研發的無塑包裝固態洗髮精，蘊含天然植物萃取成分，溫和不刺激頭皮。每塊重量約80克，相當於400ml液態洗髮精使用量。固態設計方便攜帶，適合旅行或健身使用。泡沫豐富細緻，清潔力佳且易沖洗，完全零塑膠包裝，實踐無塑生活理念。',
  },
  {
    id: 6,
    title: '簡約托特包',
    points: 150,
    image: '/images/gifts/gift-6.jpg',
    category: 'sustainable',
    series: 'sustainable',
    level: 'EXPLORER',
    stock: 99,
    actualStock: 99,
    stockStatus: 'high',
    description: '市價NT$450',
    marketPrice: 'NT$450',
    levelRestriction: 'lv1_only',
    details: '經典百搭設計的托特包，厚磅數帆布材質製作，耐磨耐用且容量充足。內層附有拉鍊口袋與多格收納設計，方便整理隨身物品。提把加厚處理，長時間揹負也不勒手。中性色調適合各種穿搭風格，是日常通勤、購物、休閒外出的最佳選擇。',
  },
  {
    id: 7,
    title: 'Re-ing 天然竹纖維便當盒',
    points: 150,
    image: '/images/gifts/gift-7.jpg',
    category: 'sustainable',
    series: 'sustainable',
    level: 'EXPLORER',
    stock: 58,
    actualStock: 58,
    stockStatus: 'medium',
    description: '市價NT$450',
    marketPrice: 'NT$450',
    levelRestriction: 'lv1_only',
    details: 'Re-ing品牌推出的環保便當盒，結合天然竹纖維與玉米澱粉複合材料，可完全生物降解。雙層設計附有密封蓋與分隔餐盤，容量約800ml。耐熱溫度達120度，可微波加熱使用。輕量化設計方便攜帶，是上班族與學生族群的環保餐具首選。',
  },
  {
    id: 8,
    title: 'SUCCULAND 多肉植物',
    points: 200,
    image: '/images/gifts/gift-8.jpg',
    category: 'sustainable',
    series: 'sustainable',
    level: 'EXPLORER',
    stock: 23,
    actualStock: 23,
    stockStatus: 'low',
    description: '市價NT$590',
    marketPrice: 'NT$590',
    levelRestriction: 'lv1_only',
    details: '來自SUCCULAND精選的多肉植物盆栽，包含陶瓷盆器與優質培養土。每株植物經過專業園藝師悉心照料，健康茁壯。多肉植物易於照顧，適合辦公桌或居家擺設，能淨化空氣並增添綠意。附贈基礎養護說明卡，即使是園藝新手也能輕鬆上手。',
  },

  // 🪴 質感創造系列 - Lv2 Creator (禮品 9-16)
  {
    id: 9,
    title: 'ekax 雲朵筆電包',
    points: 220,
    image: '/images/gifts/gift-9.jpg',
    category: 'quality',
    series: 'quality',
    level: 'CREATOR',
    stock: 99,
    actualStock: 99,
    stockStatus: 'high',
    description: '市價NT$650',
    marketPrice: 'NT$650',
    levelRestriction: 'lv2_plus',
    details: 'ekax設計的雲朵造型筆電包，防潑水尼龍布料外層，內裡為柔軟絨布保護層。適用13-14吋筆電，輕量化設計僅重300克。前方拉鍊袋可收納滑鼠、充電線等配件。簡約圓潤的外型搭配多色選擇，兼具實用性與時尚感，是數位工作者的貼心配件。',
  },
  {
    id: 10,
    title: 'smellscape 擴香石香氛禮盒',
    points: 230,
    image: '/images/gifts/gift-10.jpg',
    category: 'quality',
    series: 'quality',
    level: 'CREATOR',
    stock: 53,
    actualStock: 53,
    stockStatus: 'medium',
    description: '市價NT$700',
    marketPrice: 'NT$700',
    levelRestriction: 'lv2_plus',
    details: 'smellscape香氛品牌的擴香石禮盒，內含手工製作的石膏擴香座與10ml天然精油。擴香石運用吸水性佳的石膏材質，滴入精油後能持續散發香氛達3-5天。無需插電或點火，安全環保。精油選用薰衣草、柑橘或檀木等天然配方，為居家空間營造放鬆氛圍。',
  },
  {
    id: 11,
    title: 'MOFT 磁吸感應卡包支架',
    points: 300,
    image: '/images/gifts/gift-11.jpg',
    category: 'quality',
    series: 'quality',
    level: 'CREATOR',
    stock: 24,
    actualStock: 24,
    stockStatus: 'low',
    description: '市價NT$890',
    marketPrice: 'NT$890',
    levelRestriction: 'lv2_plus',
    details: 'MOFT創新設計的磁吸式卡包支架，優質PU皮革與強力磁鐵製成。可吸附於手機背面，收納3-5張卡片。內建隱藏式支架功能，可調整多種觀看角度。厚度僅5mm，不影響手機握感。適用於支援MagSafe的iPhone機型，是極簡主義者的理想選擇。',
  },
  {
    id: 12,
    title: '手工皮革名片夾',
    points: 310,
    image: '/images/gifts/gift-12.jpg',
    category: 'quality',
    series: 'quality',
    level: 'CREATOR',
    stock: 9,
    actualStock: 9,
    stockStatus: 'critical',
    description: '市價NT$930',
    marketPrice: 'NT$930',
    levelRestriction: 'lv2_plus',
    details: '職人手工縫製的真皮名片夾，嚴選義大利植鞣牛皮製作，隨使用時間會呈現獨特光澤與色澤變化。內部雙層設計可收納約30張名片，另有暗袋可放置重要卡片。精緻車縫線展現工藝細節，適合商務場合使用，彰顯專業品味與個人風格。',
  },
  {
    id: 13,
    title: 'Umbra 臘腸狗戒指收納座',
    points: 310,
    image: '/images/gifts/gift-13.jpg',
    category: 'quality',
    series: 'quality',
    level: 'CREATOR',
    stock: 88,
    actualStock: 88,
    stockStatus: 'medium',
    description: '市價NT$930',
    marketPrice: 'NT$930',
    levelRestriction: 'lv2_plus',
    details: 'Umbra設計的創意臘腸狗造型戒指收納座，樹脂材質製成，表面經拋光處理呈現溫潤質感。狗狗身體各部位設計為戒指收納柱，可同時收納多枚戒指、手鍊等飾品。可愛療癒的造型兼具實用功能，擺放於梳妝台或床頭櫃，為生活空間增添趣味與溫度。',
  },
  {
    id: 14,
    title: 'ROOMMI 充電感應垃圾桶',
    points: 320,
    image: '/images/gifts/gift-14.jpg',
    category: 'quality',
    series: 'quality',
    level: 'CREATOR',
    stock: 28,
    actualStock: 28,
    stockStatus: 'low',
    description: '市價NT$959',
    marketPrice: 'NT$959',
    levelRestriction: 'lv2_plus',
    details: 'ROOMMI智能充電式感應垃圾桶，採用紅外線感應技術，手靠近即自動開蓋，3秒後自動關閉。內建USB充電式鋰電池，充電一次可使用約60天。容量10公升，適合臥室、書房或浴室使用。桶身採用ABS材質，防水易清潔，配備垃圾袋固定環設計，實用便利。',
  },
  {
    id: 15,
    title: 'KINTO 提式輕巧保溫瓶',
    points: 400,
    image: '/images/gifts/gift-15.jpg',
    category: 'quality',
    series: 'quality',
    level: 'CREATOR',
    stock: 99,
    actualStock: 99,
    stockStatus: 'high',
    description: '市價NT$1,148',
    marketPrice: 'NT$1,148',
    levelRestriction: 'lv2_plus',
    details: '日本KINTO品牌的提式保溫瓶，雙層真空不鏽鋼結構，保溫效果達6小時、保冷效果達12小時。容量500ml，瓶口寬度適中便於清洗與加冰塊。獨特提把設計方便攜帶，啞光霧面塗層質感細膩。簡約俐落的外型適合各種場合使用，是質感生活的日常良伴。',
  },
  {
    id: 16,
    title: 'MOMOCONCEPT 保溫杯',
    points: 500,
    image: '/images/gifts/gift-16.jpg',
    category: 'quality',
    series: 'quality',
    level: 'CREATOR',
    stock: 55,
    actualStock: 55,
    stockStatus: 'medium',
    description: '市價NT$1,501',
    marketPrice: 'NT$1,501',
    levelRestriction: 'lv2_plus',
    details: 'MOMOCONCEPT設計的陶瓷保溫杯，優質陶瓷材質搭配食品級不鏽鋼內膽，保溫保冷效果俱佳。容量350ml，單手可握的尺寸設計。附有防漏矽膠密封圈與茶隔設計，適合沖泡茶飲。外觀呈現溫潤的陶瓷質感，多款素雅配色可選，展現獨特美學品味。',
  },

  // 🕯️ 美學先鋒系列 - Lv3 Visionary (禮品 17-24)
  {
    id: 17,
    title: 'mordeco 轉轉零錢筒',
    points: 530,
    image: '/images/gifts/gift-17.jpg',
    category: 'aesthetic',
    series: 'aesthetic',
    level: 'VISIONARY',
    stock: 36,
    actualStock: 36,
    stockStatus: 'low',
    description: '市價NT$1,580',
    marketPrice: 'NT$1,580',
    levelRestriction: 'lv3_plus',
    details: 'mordeco設計的創意轉轉零錢筒，透明壓克力材質製成，內部設有螺旋軌道。投入硬幣後會沿著軌道旋轉滑落，過程療癒有趣。上方開口設計方便投幣，底部可旋轉開啟取出零錢。容量可存放約500枚硬幣，不僅是實用的儲蓄工具，更是桌面上的趣味擺飾。',
  },
  {
    id: 18,
    title: 'Vana 香氛蠟燭暖燈',
    points: 600,
    image: '/images/gifts/gift-18.jpg',
    category: 'aesthetic',
    series: 'aesthetic',
    level: 'VISIONARY',
    stock: 19,
    actualStock: 19,
    stockStatus: 'low',
    description: '市價NT$1,790',
    marketPrice: 'NT$1,790',
    levelRestriction: 'lv3_plus',
    details: 'Vana香氛蠟燭暖燈，結合蠟燭香氛與暖燈功能的創新設計。鹵素燈泡加熱方式，無明火更安全，可調節亮度營造氛圍。適用於各種香氛蠟燭罐，透過溫熱使香氛均勻擴散。燈罩採用金屬與玻璃材質，外型典雅現代，為居家空間增添溫馨質感與嗅覺享受。',
  },
  {
    id: 19,
    title: 'MUJI 超音波芬香噴霧器',
    points: 600,
    image: '/images/gifts/gift-19.jpg',
    category: 'aesthetic',
    series: 'aesthetic',
    level: 'VISIONARY',
    stock: 16,
    actualStock: 16,
    stockStatus: 'low',
    description: '市價NT$1,790',
    marketPrice: 'NT$1,790',
    levelRestriction: 'lv3_plus',
    details: 'MUJI無印良品的超音波芬香噴霧器，超音波震盪技術將水與精油霧化噴出。水箱容量100ml，可持續運作約4小時，具備自動斷電安全設計。兩段式噴霧量調節，可依空間大小調整。簡約圓潤的白色外型，適合各種居家風格，為空間帶來舒適香氛與濕度調節。',
  },
  {
    id: 20,
    title: 'MOMAX 無線充電行動電源',
    points: 660,
    image: '/images/gifts/gift-20.jpg',
    category: 'aesthetic',
    series: 'aesthetic',
    level: 'VISIONARY',
    stock: 18,
    actualStock: 18,
    stockStatus: 'low',
    description: '市價NT$1,980',
    marketPrice: 'NT$1,980',
    levelRestriction: 'lv3_plus',
    details: 'MOMAX無線充電行動電源，容量10000mAh，支援Qi無線充電與USB-C/USB-A有線充電。可同時為3台裝置充電，無線充電功率達15W。輕薄設計厚度僅15mm，重量約200克。LED電量顯示清楚易讀，內建多重安全保護機制，是外出必備的充電利器。',
  },
  {
    id: 21,
    title: 'JWAY 砧板刀具烘乾消毒機',
    points: 830,
    image: '/images/gifts/gift-21.jpg',
    category: 'aesthetic',
    series: 'aesthetic',
    level: 'VISIONARY',
    stock: 13,
    actualStock: 13,
    stockStatus: 'low',
    description: '市價NT$2,480',
    marketPrice: 'NT$2,480',
    levelRestriction: 'lv3_plus',
    details: 'JWAY智能砧板刀具烘乾消毒機，紫外線UV-C與熱風烘乾雙重殺菌技術，殺菌率達99.9%。可同時收納3個砧板與多把刀具，內部以不鏽鋼材質易清潔。智能定時功能，烘乾消毒約60分鐘自動斷電。有效防止細菌滋生與刀具生鏽，為廚房衛生把關。',
  },
  {
    id: 22,
    title: 'Oakywood 無線充電盤',
    points: 1100,
    image: '/images/gifts/gift-22.jpg',
    category: 'aesthetic',
    series: 'aesthetic',
    level: 'VISIONARY',
    stock: 49,
    actualStock: 49,
    stockStatus: 'medium',
    description: '市價NT$3,200',
    marketPrice: 'NT$3,200',
    levelRestriction: 'lv3_plus',
    details: 'Oakywood無線充電盤，天然實木與強化玻璃製成，每件木紋紋理獨一無二。支援Qi無線充電標準，最高輸出15W快速充電。底部配備防滑矽膠墊，充電時穩固不位移。溫潤的木質觸感與簡約設計，將科技產品轉化為桌面上的藝術品，展現自然美學與現代工藝結合。',
  },
  {
    id: 23,
    title: 'Bellwood 雨傘收納架',
    points: 1100,
    image: '/images/gifts/gift-23.jpg',
    category: 'aesthetic',
    series: 'aesthetic',
    level: 'VISIONARY',
    stock: 22,
    actualStock: 22,
    stockStatus: 'low',
    description: '市價NT$3,385',
    marketPrice: 'NT$3,385',
    levelRestriction: 'lv3_plus',
    details: 'Bellwood雨傘收納架，實木與金屬結合的工藝設計，底部附有接水盤可拆卸清洗。可同時收納8-10把長短傘，傘架高度約80公分。木質底座穩固耐用，金屬傘柱經防鏽處理。簡約北歐風格設計適合玄關或辦公室使用，兼具實用收納與空間美化功能，提升居家質感。',
  },
  {
    id: 24,
    title: 'Wanu 銜月床頭燈',
    points: 1200,
    image: '/images/gifts/gift-24.jpg',
    category: 'aesthetic',
    series: 'aesthetic',
    level: 'VISIONARY',
    stock: 7,
    actualStock: 7,
    stockStatus: 'critical',
    description: '市價NT$3,500',
    marketPrice: 'NT$3,500',
    levelRestriction: 'lv3_plus',
    details: 'Wanu銜月床頭燈，創新的月型燈設計靈感來自月相變化，可360度旋轉調整照明角度。LED光源，三段式色溫調節(暖光/自然光/白光)，亮度可無段調整。觸控式開關操作直覺便利，底座採用實木與金屬材質，穩固且質感佳，為臥室營造溫馨柔和的閱讀光線。',
  },

  // 💼 品味閃耀系列 - Lv4 Luminary (禮品 25-32)
  {
    id: 25,
    title: '夏慕尼星級饗宴餐券',
    points: 1600,
    image: '/images/gifts/gift-25.jpg',
    category: 'premium',
    series: 'premium',
    level: 'LUMINARY',
    stock: 14,
    actualStock: 14,
    stockStatus: 'low',
    description: '市價NT$4,818',
    marketPrice: 'NT$4,818',
    levelRestriction: 'lv4_only',
    details: '夏慕尼鐵板燒星級饗宴餐券雙人套餐，享用精選頂級食材現場鐵板料理。套餐包含新鮮海鮮、Prime等級牛排、季節時蔬與主廚特製甜點。專業鐵板燒師傅於面前展現精湛廚藝，提供五感饗宴體驗。餐廳氛圍優雅舒適，適合慶祝紀念日或商務宴請，創造難忘的美食回憶。',
  },
  {
    id: 26,
    title: 'Porter 真皮公事包',
    points: 1950,
    image: '/images/gifts/gift-26.jpg',
    category: 'premium',
    series: 'premium',
    level: 'LUMINARY',
    stock: 18,
    actualStock: 18,
    stockStatus: 'low',
    description: '市價NT$5,850',
    marketPrice: 'NT$5,850',
    levelRestriction: 'lv4_only',
    details: 'Porter日本經典品牌真皮公事包，嚴選頂級牛皮製作，隨使用時間呈現獨特皮革光澤。內部多層隔間設計可收納15吋筆電、文件與商務用品。附可拆卸肩背帶，手提肩背兩用。精密車工展現日本職人工藝，YKK拉鍊順暢耐用，是商務人士展現專業形象的最佳選擇。',
  },
  {
    id: 27,
    title: 'LAMY 2000 鋼筆',
    points: 2300,
    image: '/images/gifts/gift-27.jpg',
    category: 'premium',
    series: 'premium',
    level: 'LUMINARY',
    stock: 26,
    actualStock: 26,
    stockStatus: 'low',
    description: '市價NT$7,020',
    marketPrice: 'NT$7,020',
    levelRestriction: 'lv4_only',
    details: 'LAMY 2000鋼筆，德國包浩斯設計經典之作，自1966年問世至今歷久不衰。筆身樹脂纖維與不鏽鋼材質，霧面處理質感細膩。14K金筆尖書寫滑順，墨水以活塞上墨系統，墨水容量大。人體工學設計長時間書寫不疲累，是書寫愛好者與收藏家的夢幻逸品。',
  },
  {
    id: 28,
    title: 'AirPods Pro 3',
    points: 2500,
    image: '/images/gifts/gift-28.jpg',
    category: 'premium',
    series: 'premium',
    level: 'LUMINARY',
    stock: 21,
    actualStock: 21,
    stockStatus: 'low',
    description: '市價NT$7,490',
    marketPrice: 'NT$7,490',
    levelRestriction: 'lv4_only',
    details: 'Apple AirPods Pro 3第三代無線藍牙耳機，搭載Apple H2晶片提供卓越音質表現。主動降噪功能再進化，阻隔環境噪音更有效。通透模式可清楚聽見周遭環境音。支援空間音訊與動態頭部追蹤，打造沉浸式聆聽體驗。IPX4防水等級，單次充電續航力達6小時，搭配充電盒總續航力達30小時。',
  },
  {
    id: 29,
    title: 'Dyson Supersonic 吹風機',
    points: 3300,
    image: '/images/gifts/gift-29.jpg',
    category: 'premium',
    series: 'premium',
    level: 'LUMINARY',
    stock: 5,
    actualStock: 5,
    stockStatus: 'critical',
    description: '市價NT$9,999',
    marketPrice: 'NT$9,999',
    levelRestriction: 'lv4_only',
    details: 'Dyson Supersonic吹風機，第五代數位馬達技術，風速強勁且運轉安靜。智能溫控系統每秒測溫40次，防止熱傷害保護髮質。附贈多款專業造型風嘴適合各種髮型需求。負離子技術減少靜電與毛躁，吹後秀髮柔順有光澤。人體工學設計平衡好握，是髮型師與質感生活者的首選工具。',
  },
  {
    id: 30,
    title: 'Apple Watch Series 11',
    points: 4300,
    image: '/images/gifts/gift-30.jpg',
    category: 'premium',
    series: 'premium',
    level: 'LUMINARY',
    stock: 4,
    actualStock: 4,
    stockStatus: 'critical',
    description: '市價NT$12,900',
    marketPrice: 'NT$12,900',
    levelRestriction: 'lv4_only',
    details: 'Apple Watch Series 11智慧手錶，搭載最新S11晶片效能更強大。全天候Retina顯示螢幕，陽光下清晰可見。進階健康監測功能包含心率、血氧、睡眠與體溫感測。支援超過100種運動模式記錄，GPS定位精準。防水50米適合游泳使用，電池續航力達18小時，是健康管理與智慧生活的最佳夥伴。',
  },
  {
    id: 31,
    title: 'LOJEL 30吋前開式行李箱',
    points: 4500,
    image: '/images/gifts/gift-31.jpg',
    category: 'premium',
    series: 'premium',
    level: 'LUMINARY',
    stock: 3,
    actualStock: 3,
    stockStatus: 'critical',
    description: '市價NT$13,205',
    marketPrice: 'NT$13,205',
    levelRestriction: 'lv4_only',
    details: 'LOJEL 30吋前開式行李箱，創新前開設計免將行李箱放倒即可取物，車站機場使用超便利。外殼德國拜耳PC材質，堅固耐撞擊且重量輕盈。TSA海關鎖與靜音雙輪設計，推行順暢安靜。內部大容量分層設計附彈性束帶，5年全球保固服務，是商務旅行與度假的最佳旅伴。',
  },
  {
    id: 32,
    title: '雲品尊榮湖景客房住宿券',
    points: 5000,
    image: '/images/gifts/gift-32.jpg',
    category: 'premium',
    series: 'premium',
    level: 'LUMINARY',
    stock: 3,
    actualStock: 3,
    stockStatus: 'critical',
    description: '市價NT$14,888',
    marketPrice: 'NT$14,888',
    levelRestriction: 'lv4_only',
    details: '雲品溫泉酒店尊榮湖景客房雙人住宿券，坐擁日月潭絕美湖景第一排視野。房內配備獨立景觀溫泉浴池，可邊泡湯邊欣賞湖光山色。含自助式早餐與迎賓下午茶，享用在地食材料理。飯店設施包含健身房、SPA與戶外泳池。專業管家服務細膩貼心，打造奢華放鬆的度假體驗。',
  },
]

export const mockOrders = [
  {
    id: 'ORD-001',
    rewardId: 1,
    rewardTitle: 'LAMY 鋼筆',
    pointsSpent: 300,
    status: 'delivered',
    createdAt: '2024-11-05',
    deliveredAt: '2024-11-08',
  },
  {
    id: 'ORD-002',
    rewardId: 3,
    rewardTitle: '竹製用品組',
    pointsSpent: 150,
    status: 'shipped',
    createdAt: '2024-11-08',
    deliveredAt: null,
  },
]

export const levelConfig = [
  {
    level: 'EXPLORER',
    name: '探索者',
    levelNumber: 1,
    minPoints: 0,
    maxPoints: 249,
    nextLevelPoints: 250,
    multiplier: 1.0,
    color: '#10b981',
    bgColor: '#d1fae5',
    gradientFrom: 'from-emerald-300',
    gradientTo: 'to-emerald-600',
    icon: 'star'
  },
  {
    level: 'CREATOR',
    name: '創造者',
    levelNumber: 2,
    minPoints: 250,
    maxPoints: 749,
    nextLevelPoints: 750,
    multiplier: 1.15,
    color: '#3b82f6',
    bgColor: '#dbeafe',
    gradientFrom: 'from-cyan-400',
    gradientTo: 'to-blue-500',
    icon: 'star'
  },
  {
    level: 'VISIONARY',
    name: '先行者',
    levelNumber: 3,
    minPoints: 750,
    maxPoints: 1499,
    nextLevelPoints: 1500,
    multiplier: 1.35,
    color: '#f59e0b',
    bgColor: '#fef3c7',
    gradientFrom: 'from-amber-300',
    gradientTo: 'to-amber-600',
    icon: 'star'
  },
  {
    level: 'LUMINARY',
    name: '閃耀者',
    levelNumber: 4,
    minPoints: 1500,
    maxPoints: 999999,
    nextLevelPoints: null,
    multiplier: 1.7,
    color: '#a78bfa',
    bgColor: '#ede9fe',
    gradientFrom: 'from-purple-300',
    gradientTo: 'to-purple-600',
    icon: 'star'
  },
]